// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9QtgCgb3aHctlDkVWEje2B-KRJFESRDU',
    appId: '1:394271426095:web:f83d2deb3d00cfed1628da',
    messagingSenderId: '394271426095',
    projectId: 'loja-esdm',
    authDomain: 'loja-esdm.firebaseapp.com',
    storageBucket: 'loja-esdm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ1MxPpHdHXGYj1KmRvITwmDDt-fQpLOI',
    appId: '1:394271426095:android:1248fe2a82e791101628da',
    messagingSenderId: '394271426095',
    projectId: 'loja-esdm',
    storageBucket: 'loja-esdm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRayFSkySXR8YDJnQ2O4rykVpuir2xIJQ',
    appId: '1:394271426095:ios:04c3c0621f5f12a31628da',
    messagingSenderId: '394271426095',
    projectId: 'loja-esdm',
    storageBucket: 'loja-esdm.appspot.com',
    iosClientId: '394271426095-lp0afkcia3d5b86dtagnit7pg1nai569.apps.googleusercontent.com',
    iosBundleId: 'com.example.lojaVirtual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRayFSkySXR8YDJnQ2O4rykVpuir2xIJQ',
    appId: '1:394271426095:ios:04c3c0621f5f12a31628da',
    messagingSenderId: '394271426095',
    projectId: 'loja-esdm',
    storageBucket: 'loja-esdm.appspot.com',
    iosClientId: '394271426095-lp0afkcia3d5b86dtagnit7pg1nai569.apps.googleusercontent.com',
    iosBundleId: 'com.example.lojaVirtual',
  );
}
